# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
        exclude: >-
          (?x)^(
            tools/autotune_grid/xyz_to_vab/pyratemp.py|
          )$
-   repo: local
    hooks:
    -   id: prettify
        name: Run prettify
        entry: ./tools/prettify/prettify.py
        language: script
        files: '.*\.(F|f90)$'
        exclude: >-
          (?x)^(
            tools/.*|
            src/base/base_uses.f90|
            src/common/util.F|
          )$
